### ISSUE TITLE
No encoding supplied: defaulting to UTF-8.

### ISSUE THREAD

**Issue by karthik** [karthik/rdrop2#100]
This is a default message that prints on most call. Should we suppress this?

**Comment by ClaytonJY** [comment]
Where in the stack is the message thrown? I know I see it on `drop_read_csv` all the time, does it show up elsewhere too? Can/should we set the encoding, or add it as an arg with a default of `utf-8`?

**Comment by ClaytonJY** [comment]
Assigning this to 0.8, but could easily punt to 0.9.

**Comment by ClaytonJY** [comment]
not entirely sure where this still shows up; I swear I've seen it recently, but perhaps only on old-API functions?

**Comment by karthik** [comment]
I don't see these anymore now that we've fully migrated to V2. So this may have resolved itself. But let's do a full check before closing it out.
