### ISSUE TITLE
Remove data.table dependency

### ISSUE THREAD

**Issue by karthik** [karthik/rdrop2#101]
Currently the package uses both dplyr and data.table. Should remove at least one and refactor code using the other.

**Comment by ClaytonJY** [comment]
I vote `dplyr`, we use at least two commands from it right now (`tbl_df` in `drop_dir` and `drop_search`, `select` in `drop_dir`), while we only use `rbindlist` from `data.table` (in `drop_search`, `drop_delta`, and `drop_history`).

We probably need to keep returning tibbles in a few places to keep some backwards compatibility, but I could imagine a future where we don't coerce anything to tibbles; depends how much we want to be a simple wrapper vs. having more high-level, abstracted functionality.

**Comment by karthik** [comment]
Sounds good to me.
