### ISSUE TITLE
standardize use of uuid in testing

### ISSUE THREAD

**Issue by ClaytonJY** [karthik/rdrop2#112]
Some of the older tests still use hardcoded file/folder names in their tests. This is usually fine, but problems can arise when running multiple tests simultaneously (race condition), or if a test errors in a way that prevents proper cleanup.

This should be a lot harder to trigger if we rewrite the older ones to make filenames with `uuid::UUIDgenerate()` like we've started doing more recently.

**Comment by karthik** [comment]
Fixed
