### ISSUE TITLE
error while downloading .rda files

### ISSUE THREAD

**Issue by rohitpandharkar** [karthik/rdrop2#13]
Hi,

if i have a .rda file in dropbox, how do I download it?

this happens:
drop_get('duncan.rda')
Error: Path exists and overrwrite is FALSE

**Comment by rohitpandharkar** [comment]
Got it!  You may pls add this to README

# UPLOAD
ax <- c(1,2,3,4,5)
save(ax, file = "myfile.rda")
# upload to a specific folder
drop_upload('myfile.rda', dest = "drop_test")

# DOWNLOAD
# or add path if file is not in root
drop_get("drop_test/myfile.rda")
mydata <- get(load('myfile.rda'))

**Comment by karthik** [comment]
Or you can just add `overwrite = TRUE` to `drop_get`.
I've carefully documented all of this in help.
after downloading, a simple `load('myfile.rda')` should pop it back into Global Env.
