### ISSUE TITLE
Make templates for issues and PR's

### ISSUE THREAD

**Issue by ClaytonJY** [karthik/rdrop2#133]
Probably worth doing.

- [x] [issue template](https://help.github.com/articles/creating-an-issue-template-for-your-repository/)
- [x] [PR template](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/)

**Comment by karthik** [comment]
Suggestion. Ask people to add this at the bottom of their issue

```
<details> 
# paste the output from `devtools::session_info()` here
</details>  
```

It looks like this:

<details>
Session info ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.1 (2017-06-30)
 system   x86_64, darwin15.6.0        
 ui       RStudio (1.0.153)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/Los_Angeles         
 date     2017-09-30                  

Packages --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 package   * version date       source                         
 base      * 3.4.1   2017-07-07 local                          
 compiler    3.4.1   2017-07-07 local                          
 coyote      0.3     2017-09-13 Github (karthik/coyote@acad466)
 datasets  * 3.4.1   2017-07-07 local                          
 devtools  * 1.13.3  2017-08-02 CRAN (R 3.4.1)                 
 digest      0.6.12  2017-01-27 CRAN (R 3.4.0)                 
 graphics  * 3.4.1   2017-07-07 local                          
 grDevices * 3.4.1   2017-07-07 local                          
 memoise     1.1.0   2017-04-21 CRAN (R 3.4.0)                 
 methods   * 3.4.1   2017-07-07 local                          
 stats     * 3.4.1   2017-07-07 local                          
 tools       3.4.1   2017-07-07 local                          
 utils     * 3.4.1   2017-07-07 local                          
 withr       2.0.0   2017-07-28 CRAN (R 3.4.1)          
</details>
