### ISSUE TITLE
Error in drop_upload(filePath, dest = outputDir1) :    unused argument (dest = outputDir1)

### ISSUE THREAD

**Issue by navenachaitoo** [karthik/rdrop2#134]
@karthik I've been using rdrop2 for a few months now in a Shiny app to save data that's refreshed daily and then read the appended files to visualize trends. It's been working reliably well up until today. I encountered an issue where my app is no longer running and I'm getting 

> Error in drop_upload(filePath, dest = outputDir1) : 
  unused argument (dest = outputDir1)

Here's an example of my code using the mtcars data:
```
library(rdrop2)
library(datasets)

data("mtcars")

outputDir1<-"Test Dropbox Folder"

saveData1 <- function(data) {
  # Create a unique file name
  fileName <- paste0(Sys.Date(),".csv")
  # Write the data to a temporary file locally
  filePath <- file.path(tempdir(), fileName)
  write.csv(data, filePath, row.names = FALSE, quote = TRUE)
  # Upload the file to Dropbox
  drop_upload(filePath, dest = outputDir1)
}

loadData1 <- function() {
  # Read all the files into a list
  filesInfo <- drop_dir(outputDir1)
  filePaths <- filesInfo$path
  data <- lapply(filePaths, drop_read_csv, stringsAsFactors = FALSE)
  # Concatenate all data together into one data.frame
  data <- do.call(rbind, data)
  data
}

saveData1(mtcars)
loadData1()
```

Any help would be much appreciated! Thanks!

**Comment by navenachaitoo** [comment]
Here's my session info:

> > sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Sierra 10.12.6

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rdrop2_0.8

loaded via a namespace (and not attached):
 [1] assertive.sets_0.0-3       codetools_0.2-15           assertive.data.us_0.0-1    assertive.types_0.0-3      assertive.properties_0.0-4
 [6] R6_2.2.2                   jsonlite_1.5               assertive.base_0.0-7       magrittr_1.5               assertive.models_0.0-1    
[11] assertive.code_0.0-1       httr_1.3.1                 stringi_1.1.5              assertive.strings_0.0-3    curl_2.8.1                
[16] assertive.matrices_0.0-1   assertive.reflection_0.0-4 assertive.data_0.0-1       assertive_0.3-5            assertive.datetimes_0.0-2 
[21] tools_3.3.2                assertive.numbers_0.0-2    assertive.files_0.0-2      assertive.data.uk_0.0-1    openssl_0.9.6             
[26] knitr_1.17

**Comment by cfitzge1** [comment]
Hey @navenachaitoo, I was having a similar issue until I looked at the documentation. The argument for director is no longer `dest` it is `path`

**Comment by navenachaitoo** [comment]
@cfitzge1 Thanks! That worked for me. Now, I'm having an issue with the loading the data back in though. I get this error:  Error in bind_rows_(x, .id) : Argument 11 must be length 1, not 3 

I checked the data and I still have the same number of columns so I don't think that's the issue. Is there an issue with my load function above that you can see? Thanks again!

**Comment by ClaytonJY** [comment]
@cfitzge1 & @navenachaitoo very sorry about this issue; yes, the argument has changed. We should have communicated that more clearly, but fair warning, I think every function now has a slightly different signature then before, so you should check all your used of `rdrop2` functions.

We think this was necessary because of how dramatically the underlying Dropbox API changed, but we also were in a bit of a crunch trying to get 0.8 out in time.

**Comment by navenachaitoo** [comment]
thanks @karthik -- you are right, the issue is with the "path" column in the code above.

**Before**
filesInfo <- drop_dir(outputDir1)
filePaths <- filesInfo$path

**After**
filesInfo <- drop_dir(outputDir1)
  filePaths <- filesInfo$path_lower

Still having issues republishing the app to Shiny Server :(

**Comment by ClaytonJY** [comment]
@navenachaitoo I think you're seeing #135; when the metadata is nested (e.g. if the object is shares), we can't just call `bind_rows` on it. We fixed this by flattening the list rather inelegantly in 0.8.1 (now on `master`, submitted to CRAN last night), but are trying to think more carefully about what to do with these metadata objects the API returns for many of these endpoints.

We love tibbles too, so I think we want to maintain a tibble output. Do you have a preference between these two?
1. flatten list, so we have columns like `sharing/something`, `sharing/somethingelse` (could change separator or remove prefix)
2. nest list into list-cols, so we have a single `sharing` list-column, where each row has it's own `something` and `somethingelse` components, that the user could then un-nest as needed

**Comment by ClaytonJY** [comment]
@navenachaitoo as for your shiny problems, I'd check a few things:
1. make sure you regenerate your auth token; the API endpoint is stored in the token, and has changed, so old token will no longer work
2. make sure that token is saved as an RDS and bundled with your app. in `global.R` (or `server.R` above the `shinyServer` block) you should read the token into `drop_auth` like `drop_auth(rdstoken = "path/to/token.rds")

**Comment by navenachaitoo** [comment]
@ClaytonJY 

Regenerating the token fixed this. Thanks!
