### ISSUE TITLE
Error in fetch(key) :    lazy-load database '/Library/Frameworks/R.framework/Versions/3.3/Resources/library/rdrop2/help/rdrop2.rdb' is corrupt

### ISSUE THREAD

**Issue by navenachaitoo** [karthik/rdrop2#137]
@karthik  A call to drop_dir() causes this error.

**Comment by Fablepongiste** [comment]
did you try starting from clean RSession ? Usually happens when # versions of packages have been loaded / tried to be loaded

**Comment by ClaytonJY** [comment]
@navenachaitoo I think @Fablepongiste is right; this is unlikely an issue with rdrop2 directly.

Try restarting R, and if that doesn't work, please provide a reproducible example, including authentication and uploading before the `drop_dir` call so we can replicate the issue.

**Comment by navenachaitoo** [comment]
Will do! Most likely later tonight. Thanks to you all for being so on top of this and so helpful. Really appreciated! 

Navena Chaitoo

**Comment by navenachaitoo** [comment]
Restarting R didn't do it but reinstalling rdrop2 did! Thanks @Fablepongiste and @ClaytonJY! My app is now back up and running! Woot!
