### ISSUE TITLE
Duplicate thumbnail

### ISSUE THREAD

**Issue by ClaytonJY** [karthik/rdrop2#140]
The two top-level files `drop.png` and `drop_thumbnail.png` are the same file. We use the latter in the README, and never use the former. Should delete former. Might as well chuck the keeper in `docs/`, too.

**Comment by karthik** [comment]
The thumbnail was meant to be used in the README because markdown does not allow you to specify image sizes. I believe this was lost in a rebase (definitely my fault). Also just realized that we lost Caleb as a contributor. Got to fix that by the next update.

________________________________

**Comment by karthik** [comment]
Good idea to chuck stuff in docs. But we should discuss the plan for automated doc deployment first (related to the outstanding PR)

________________________________

**Comment by ClaytonJY** [comment]
@karthik ah dang, didn't realize pkgdown uses that, too. For the github-specific stuff, it seems the options are `docs/`, `.github/`, or top-level. For the logo, I see `dplyr` uses `man/figures`. Should I make either/both changes in #141?
