### ISSUE TITLE
drop_exists, drop_create, drop_dir throw the same error

### ISSUE THREAD

**Issue by cfitzge1** [karthik/rdrop2#142]
Hey all,

When I run `drop_exists` or `drop_create` on a folder two levels down I get this error:
`Error in drop_list_folder(path, recursive, include_media_info, include_deleted,  : 
  Conflict (HTTP 409).`

To clarify, lets say I have this structure in my Dropbox `/Home/2017-10-01/` and nothing else.

If I call `drop_exists(path = "/Home/2017-10-01/Hourly/minute/", dtoken = dbx_token)` I get that error, when before this latest update it would just return `FALSE`. 

I get the same error with `drop_create` if I'm wanting to create a folder within a folder that both dont exist. To follow this same example:

If I call `drop_create(path = "/Home/2017-10-01/Hourly/minute/", dtoken = dbx_token)` I get the same error.

**Comment by ClaytonJY** [comment]
cc @karthik

**Comment by karthik** [comment]
Thanks for the report @cfitzge1 I'm digging into this today.

**Comment by karthik** [comment]
@cfitzge1 This is an excellent report. The issue is that `drop_exists` does a directory listing one level above than requested. So for example, if you are checking to see if a folder named `test` exists and run `drop_exists('test')`, it is really listing one level above (in this case, the root) and grepping the results for a folder/file named `test`.

However, as you'v noted, it will fail two (or more levels down) because it is then trying to list a the contents of a folder that does not (yet) exist, resulting in the 409 error. One solution:

```
devtools:::install_github("karthik/rdrop2", ref = "patch-142)
# Then run your code
```

My guess is that this will fix all the issues above, but will create performance problems on really large dropbox accounts. I will work on a solution for this.

**Comment by karthik** [comment]
One other idea: 

replace https://github.com/karthik/rdrop2/blob/patch-142/R/drop_file_ops.R#L292 with:

```
  safe_dir_check <- purrr::safely(drop_dir, otherwise = FALSE, quiet = TRUE)
  dir_listing <- safe_dir_check(path = '/', recursive = TRUE, dtoken = dtoken)
```

This will not go through the motion of listing then grepping the entire account, but will try to dir list one level above the requested nesting. However, the failure is trapped by safely and will return `FALSE` as expected if object is not found.

Thoughts on this @ClaytonJY

**Comment by ClaytonJY** [comment]
@karthik as discussed, I think having `drop_exists` use `safely` + `drop_get_metadata` will be more robust than stripping-a-level and using `drop_dir`. Also should be much more time-efficient in a case where that directory has a huge amount of stuff, requiring multiple calls to `drop_list_files_continue`.

**Comment by cfitzge1** [comment]
Thanks so much for looking into this!

**Comment by karthik** [comment]
@cfitzge1 This issue is fixed now. Please reinstall the package from GitHub. We really appreciate your bug report. Please let us know if any other issues arise.  🙏

```r
# install.packages("devtools") # in case you don't have it
devtools::install_github("karthik/rdrop2")
```

🎉

**Comment by Tixierae** [comment]
I have a similar problem, but with 'drop_share'. It returns 'Error in drop_share('folder_name') : Conflict (HTTP 409). I am using the latest version of rdrop2 from GitHub.

**Comment by ClaytonJY** [comment]
@Tixierae could you file a new issue with a reproducible example, starting with the creation of a new folder and uploading one or more files to it?

**Comment by Tixierae** [comment]
@ClaytonJY thanks, but fortunately, after reinstalling httpuv and shiny from GitHub (with devtools) and a reboot, it now works fine.
