### ISSUE TITLE
Problem acces DropBox account via R and rdrop2

### ISSUE THREAD

**Issue by jjpcaste** [karthik/rdrop2#143]
Hi. Today, october 2th 2017, acces to DropBox accounts via R and rdrop2 failed. I have checked API DropBox pages. API v.1.0 is drepecated from past september 28th. May be in connection voth problems?

**Comment by Fablepongiste** [comment]
You need the latest version v0.8.0 or above as mentioned in readme and on news file. 
https://github.com/karthik/rdrop2/blob/master/NEWS.md

**Comment by Fablepongiste** [comment]
Can close this issue which is not one.
