### ISSUE TITLE
"path" argument description in documentation

### ISSUE THREAD

**Issue by KasperSkytte** [karthik/rdrop2#147]
In the documentation of drop_search, drop_get, and possibly others, the description of the path argument says: "This is required The path to the new folder to create relative to root.". I don't think it makes sense. Perhaps a copy/paste typo? :)

**Comment by karthik** [comment]
It comes from a documentation template https://github.com/karthik/rdrop2/blob/master/man-roxygen/path.R I will update this shortly.
