### ISSUE TITLE
Authentication ok; but drop_dir() drop_acc() problems

### ISSUE THREAD

**Issue by cainesap** [karthik/rdrop2#152]
Hello,

Dropbox access through rdrop2 was working fine for me when I last used it (about 2 months ago) -- thank you for the great library!

But now, if I run drop_dir() and drop_acc() I've encountered problems.

With `drop_acc() %>% data.frame()` I get:
```
       error
1 v1_retired
```

And with `drop_dir()` I get:
```
data frame with 0 columns and 0 rows
```

I cleared rdrop2 from the connected apps in my Dropbox settings, and re-authorised (this worked fine), but with the same result. Please could you help?

**Comment by ClaytonJY** [comment]
@cainesap have you updated your version of `rdrop2`? Dropbox recently retired the original API, so you'll need `rdrop2 v0.8.1` to continue accessing dropbox from R; you can install this from CRAN. You may need to re-authorize again, to get an updated ouath token.

**Comment by ellisvalentiner** [comment]
@cainesap Dropbox retired v1 of their API on 2017-09-28. If you install the latest version of rdrop2 you should be fine.

**Comment by karthik** [comment]
@cainesap As others have mentioned, your old auth is still working but the version 1 API is itself now deprecated. Please update the package from GitHub 

```
devtools::install_github("karthik/rdrop2") 
```
and everything should work fine again.

**Comment by cainesap** [comment]
Thanks everyone -- package updated and all fine again now!
