### ISSUE TITLE
Error message with drop_auth()

### ISSUE THREAD

**Issue by aousabdo** [karthik/rdrop2#155]
I am trying to use rdrop2 for the first time. I followed the instructions on github but I keep getting this error message when I try to run drop_auth(): 

Invalid redirect_uri. When response_type=code, redirect_uri must start with "https://", unless it's a localhost URI

When this command is run from RStudio a web page opens and I get the error message above. I am logged in into my dropbox account on the same browser.

**Comment by aousabdo** [comment]
Apparently this has to do with httpuv not being installed on my system. Problem solved after installing httpuv

**Comment by UlrikeNaumann** [comment]
what is httpuv?

**Comment by ClaytonJY** [comment]
@UlrikeNaumann it's an R package, and a (suggested) dependency of the `httr` package we use in `rdrop2`, which we might need a harder dependency on. Github page here: https://github.com/rstudio/httpuv

**Comment by mkirzon** [comment]
Confirming that install of httr was the missing ingredient for me as well. Would be in favor of a harder dependency
