### ISSUE TITLE
Problem with accessing folders/files outside my root folder

### ISSUE THREAD

**Issue by lbusett** [karthik/rdrop2#160]
Hi, 

   I'm trying to use the package to access files contained in a dropbox "shared" between multiple users. I managed to authorize/authenticate to access the dropbox using `drop_acc()` just fine. However, when trying to navigate the contents I only manage to see the files contained in my root folder (the one given by: 

```
> drop_acc()$root_info$home_path
[1] "/Lorenzo Busetto"
```

Is there a way to get access the other folders in the dropbox (specifically, other folders containing shared data, and for which I have access rights granted as member of a group). 

Thanks in advance,

Lorenzo

(working in R3.4.3, with rdrop2 0.8.1 from CRAN)

**Comment by ClaytonJY** [comment]
@lbusett are you sure you've "added" the shared folders to your account? I just tested with an account of mine that has both group folders and one-off shared folders from outside the group, and they all appear when I do `drop_dir()`. You don't see them at the root level?

I'm not sure `home_path` is important; I don't even get that for my account.

**Comment by lbusett** [comment]
@ClaytonJY    
   thanks for the answer.  Could you explain what do you mean by "adding the shared folders to your account?"
How should I do that? I checked in the dropbox interface, but was not able to find that kind of functionality. 

Lorenzo

**Comment by lbusett** [comment]
@ClaytonJY  I forgot to mention that the dropbox I am trying to access is a "Business" one. It seems that it could behave differently than "normal" ones:

https://github.com/ncw/rclone/issues/2003

Lorenzo

**Comment by ClaytonJY** [comment]
@lbusett I also have a business Dropbox account at my day job, and as far as I can tell,`rdrop2` works just fine.

If you go to https://www.dropbox.com/work, do you see all the folders you're looking for? I have both a Team Folder and several "Everything Else" folders shown in that view, all of which appear if I call `drop_dir()`. Do you see different behavior?

**Comment by ClaytonJY** [comment]
@lbusett is it possible that with `rdrop2` you logged into your personal account, not your work account? The dropbox.com UI tends to conflate the two, signing into one might sign you into both, but the API itself has a level of separation between the two.

If you do `drop_auth(new_user = TRUE)` that will re-start the auth flow, and in the browser you should be able to select Personal or <Business Name> accounts; choose the latter and see if anything changes. If you don't get both options or don't get defaulted to the business account, you need to sign out of Dropbox in that browser, and re-sign in to your business account.

**Comment by lbusett** [comment]
Still no luck... and (as far as I remember...) I do not have a personal account linked to the same mail address.

**Comment by ClaytonJY** [comment]
@lbusett they wouldn't be the same email address, but different ones. Do you have a personal account under a separate email? If `/work` is redirecting to `/home`, that suggests you're logged in as a personal account; I get the opposite redirection when logged into my business account.

What does `drop_acc()$account_type` return?

**Comment by lbusett** [comment]
> drop_acc()$account_type 
$.tag
[1] "business"

**Comment by ClaytonJY** [comment]
Hmm...my best guess is that your `rdrop2` token is authenticated with your business account, but you're logged into the UI as your personal account, thus why you're seeing two sets of folders. I just flipped back and forth between my personal and business accounts both in the browser and with rdrop2, and get the same views from either.

**Comment by lbusett** [comment]
That's strange....
 
   I will maybe try tomorrow to add a fresh new user to the team, and see if it changes anything.
Thanks anyway for the moment!

Lorenzo

**Comment by ClaytonJY** [comment]
@lbusett sorry I can't be more helpful, if I could replicate the behavior you're seeing I'd have a better shot at diagnosis, but so far I haven't been able to do that.

Trying a fresh new user is a great idea; let me know how that goes!

**Comment by lbusett** [comment]
@ClaytonJY 

I still was not able to test with a new user. However, I wonder if this could be related to the "new team folder structure" of dropbox business described here: https://www.dropbox.com/en/help/business/team-folders. On that page, it is stated that **only "Some teams have access to the new team folder structure"**

I indeed see a "purple" folder with my name "on top", so it appears that I have the "new team folder structure". Is it the same for you ? (i.e., do you see the "purple folder") in your business account?

**Comment by ClaytonJY** [comment]
@lbusett good catch! I'm _not_ in the new "team space" setup, but on the older "team folder" setup.

So if you have some different kind of folder, that must be the problem, right? But `rdrop2::drop_dir` relies on the [`list_folder` API endpoint](https://www.dropbox.com/developers/documentation/http/documentation#files-list_folder), and the most relevant thing I see is the `include_mounted_folders` arg, which we explicitly set to TRUE (the default) inside `rdrop2`.

Now, perhaps unlike _my_ "team folder", your "team space" isn't considered as being in the root folder for your user, and is instead some other top-level folder. The [`list_folders` (plural) endpoint](https://www.dropbox.com/developers/documentation/http/documentation#sharing-list_folders) might reveal that...but we don't expose that endpoint currently. If we could _guess_ the right `path`, we could hopefully feed that into `drop_dir` to list the folders contents, and then use those paths to `drop_download` or whatever else.

If you click on one of these folders you don't see with `drop_dir`, what does the URL look like? All my top-level folders, which I do see with `drop_dir`, have URLs like `dropbox.com/work/<folder_name>/`, so if you see something else that might be the hint we need.

Another thing to check: what do you see in the "Sharing" section of the web UI? Mine is empty, but I think this is where you'd see folders that have been shared with you, but which you haven't added or "mounted". Do you see any of your folders of interests in there?

**Comment by lbusett** [comment]
@ClaytonJY I reply in line: 

> If you click on one of these folders you don't see with drop_dir, what does the URL look like? All my top-level folders, which I do see with drop_dir, have URLs like dropbox.com/work/<folder_name>/, so if you see something else that might be the hint we need.

All my top-level folders are accessible through URLs like dropbox.com/**home**/<folder_name>/

So, maybe just directing the call of drop_dir to "home" instead than to "work" could do the trick? I could clone the repo and see if it works. 

`Another thing to check: what do you see in the "Sharing" section of the web UI? Mine is empty, but I think this is where you'd see folders that have been shared with you, but which you haven't added or "mounted". Do you see any of your folders of interests in there?`

My "sharing" folder is empty as well.

**Comment by lbusett** [comment]
Fore reference, after some further digging, this seems related: 

https://www.dropboxforum.com/t5/API-Support-Feedback/API-V2-Access-team-folders-of-bussines-plan-with-Folder-Files/td-p/268044

, which lead to : 

https://www.dropbox.com/developers/reference/namespace-guide

HTH!

**Comment by ClaytonJY** [comment]
That does help, but you'll have to hack around `rdrop2` to make it work since we aren't setup to handle namespaces.

First you'll need to find the namespace ID of the root folder, which should be in `drop_acc()$root_info$root_namespace_id` (and different from `drop_acc()$root_info$home_namespace_id`).

Then you need to construct paths like `ns:<id from above>/<folder you care about>`. However, if you pass that path to `drop_dir`, it will get a slash prepended, which I assume will cause an error response from Dropbox. You can instead try using `rdrop2:::drop_list_folder`, which I think should _work_, but the response will be a nested list instead of a tibble, and if there are many results you may need to use `drop_list_folder_continue` to get more.

Unfortunately, that's the best I can offer for now :(

**Comment by lbusett** [comment]
Hi, 
   
  unfortunately, also this does not seem to work. I mean: If I do: 

```
path = paste0("ns:", drop_acc()$root_info$home_namespace_id)
drop_list_folder(path)
```

it works, but I only get results for my "user" folder. 

If I do: 

```
path = paste0("ns:", drop_acc()$root_info$root_namespace_id)
drop_list_folder(path)
```
I get instead: 

> Error in drop_list_folder(path) : Conflict (HTTP 409)

I do not know if related, but here: 

https://www.dropboxforum.com/t5/API-Support-Feedback/Can-t-get-path-with-ns-prefix-to-work-in-2-files-list-folder/td-p/277821

it is reported that apparently to acces those namespaces one should use the "Dropbox-API-Path-Root header" ( do not really know what this means and if helps, sorry...)

**Comment by ClaytonJY** [comment]
@lbusett can you try `root_namespace_id` instead of `home_namespace_id`?

You may be right that we need to set that header, but if that's the case I really can't help you; you'll have to craft your own requests with `httr`.

**Comment by lbusett** [comment]
Using `path = ""` the call does not error. 

Unfortunately the results still only show the foldes below my "users folder" (i.e., the same I get with "drop_dir")

I wonder if this may be relevant: 

> Linking to a team
> Developers will need to direct a Dropbox Business team administrator through the standard OAuth 2.0 flow to install their application on a Dropbox Business team. The OAuth response/redirect will include an additional team_id field that can be used to uniquely identify a team.
> 
> Dropbox Business API OAuth tokens can enable extensive access to team data, so it is your responsibility to properly secure them server-side. They should never be cached in insecure environments or downloaded to client devices.

> Member file access
> A Dropbox Business app can make calls to the Dropbox API for any member of the Dropbox Business team. Your app must have Team member file access permission.
> 
> To make calls on a member's behalf, use the OAuth token **granted to the app by the team**. Specify the member_id of the user that the app wants to act on using a custom HTTP header called Dropbox-API-Select-User.

Indeed, if I look at the administration panel of the dropbox, I have a specific "place" within the settings where I can authorize "team apps". `rdrop2` instead seems to be authorized at the "user level" (i.e., if I select my user, I get to a panel with authorized apps for that user, and after running drop_auth() I find rdrop2 as an authorized application).

**Comment by lbusett** [comment]
Hi, 

    thanks for the suggestion. However, I do not think I will try that, since I do not really know what I am doing and I do not want to "compromise" security somehow. Also, even if I was able to "connect", then probably I would have to tweak the rdrop2 API to implement functionality, and I do not have the time (and skills) at this time. 

Thanks again for all your help! I am sorry that it did not lead anywhere: I hope I did not waste too much of your time (well, at least you will already know what's happening if/when someone else stumbles upon this problem...) 

Lorenzo

**Comment by ClaytonJY** [comment]
@lbusett you certainly didn't waste my time; you've opened my eyes to a use-case I wasn't even aware of, and were quite patient in explaining to me your situation. I'm sorry I can't help you as of now, but I hope there's room to improve this in the future.

I'm going to close this issue, but I'll be keeping this use-case in mind when I am able to further develop this package or its replacement.
