### ISSUE TITLE
Cascading errors from drop_dir(..., file_limit = 1000,...)

### ISSUE THREAD

**Issue by noamross** [karthik/rdrop2#20]
The file count limit in `drop_dir()` causes cascading errors, primarily because `drop_dir()` is used in `drop_exists()`, which in turn is used as an error checker in other conditions.  So when I go to `drop_get()` a file in a directory of over 1000, I get an error because it says the file doesn't exist.

Some suggestions:
1. `drop_dir()` should print a verbose warning when it gets an error in response to asking for a folder with too many files. ("406 Error: Folder contains more entries than file_limit (1000)")
2.   For `drop_exists()`, don't use `drop_dir()` to determine file existence but instead make a request to the `/metadata/...` for the file.  (A function to get the metadata of one file might be useful, anyway).
3.   Since `drop_dir()` is used internally elsewhere, perhaps this parameter should be a package option.
4.   Or `drop_dir()` could automatically run again with a higher file limit if encountering this error.

Of these, (1) and (2) seem best.

(I note that the docs say the default is `file_limit` 10,000 but the current actual default is 1000.  I think this is because the docs are taken straight from the Dropbox API docs.)

**Comment by karthik** [comment]
There is a file limit option in `drop_dir`. It was set at 1k but I bumped it to 10k. (re 1 and 3, 4)
2. It doesn't make sense to write a new call to `metadata/` since that would be essentially rewriting the function. I'll push my cleanup branch shortly and that should take the default limit up to 10k.

**Comment by karthik** [comment]
The latest PR (once Travis finishes) should fix this issue. 

> I note that the docs say the default is file_limit 10,000 but the current actual default is 1000. I think this is because the docs are taken straight from the Dropbox API docs

Correct. For most things it didn't seem worth rewriting the argument descriptions. I set it to 10k.
