### ISSUE TITLE
Archival on Cran

### ISSUE THREAD

**Issue by tadhg-moore** [karthik/rdrop2#207]
Recently (2023-10-24), this package has been archived on [CRAN](https://cran.r-project.org/web/packages/rdrop2/), due to it's dependency on the package [assertive](https://cran.r-project.org/web/packages/assertive/). This seems like it would be an easy fix and would be helpful to have this back on CRAN. I can have a look and see what I can do, but wondering if the maintainers are interested in that.

**Comment by laresbernardo** [comment]
Yes!! Thanks @tadhg-moore looking forward for the update in CRAN!
