### ISSUE TITLE
roadmap for next version

### ISSUE THREAD

**Issue by karthik** [karthik/rdrop2#22]
I hope to release the next CRAN version towards the end of May. Planned features

- Support for Deltas, so Shiny users can update based on file changes
- Progress bars for file uploads. The package can support uploads of any size, but currently it's not possible to predict progress on large files. Same with downloads.

If any users have other feature requests, please post below. The late May timeline works with CRAN's update policies although features will become available sooner here.

**Comment by tanthiamhuat** [comment]
can your drop2 works with Intuitics? See https://www.intuitics.com
I actually do the following steps:
Step 1: In my local R:
library(rdrop2)
db.auth <- drop_auth()
saveRDS(db.auth, "db.auth")

Step 2: Upload db.auth as Intuitics app data.
Then in the Intuitics script:
db.auth <- readRDS("data/db.auth")

Step 3: 
drop_dir('Public/Apps/OnlineSurvey', db.auth)
but above does not work.



and when you need to make a Dropbox call, just use the db.auth as an argument, e.g.:




db_acc(db.auth)

**Comment by karthik** [comment]
The issue is that R will read arguments by position if you do not name it. So `db.auth` as the second argument is being passed as `file_limit`. You can fix this by doing 
```r
drop_dir('Public/Apps/OnlineSurvey', dtoken = db.auth)
```

**Comment by tanthiamhuat** [comment]
thanks so much for your reply, I would test out your suggestion and let you know its outcome.

**Comment by karthik** [comment]
Both features are now in place.

**Comment by tanthiamhuat** [comment]
drop_dir('Public/Apps/OnlineSurvey', dtoken = db.auth) will ask for authorization code. where do I get the authorization code?

**Comment by tanthiamhuat** [comment]
In my local R, I have below code:
install.packages("rdrop2")
library(rdrop2)
db.auth <- drop_auth()
saveRDS(db.auth, "db.auth")

## That saved file db.auth is uploaded to Intuitics in 'data' directory.
In Intuitics, I have below:
install.packages("rdrop2")
base::library(rdrop2)
db.auth <- readRDS("data/db.auth")
test <- function()
	{
	 output <- drop_dir('Public/Apps/OnlineSurvey', dtoken = db.auth)	
  }
which the output returns NULL.

In my local R, 
> drop_dir('Public/Apps/OnlineSurvey')
Source: local data frame [2 x 5]

                               path mime_type    root bytes
1 /public/apps/onlinesurvey/BUS.csv  text/csv dropbox    49
2 /public/apps/onlinesurvey/MRT.csv  text/csv dropbox    47
Variables not shown: modified (chr)

I need the output in Intuitics to return the 2 .csv files as what I have in local R, but this is not what I get.

**Comment by karthik** [comment]
In the future please do not hijack an existing issue. Start a new topic since this is completely unrelated to my roadmap. All of your problems relate to your understanding of R and not to do with any issues of my package.

> which the output returns NULL.

That is because you did not return anything from the function. You also did not explicitly pass that token to the function which will cause problems sometimes.

The correct way would be this.

```r
db.auth <- readRDS(path, "data/db.auth")
test <- function(path, token)
{
drop_dir(path, dtoken = token)
}

test('Public/Apps/OnlineSurvey', db.auth)
```
