### ISSUE TITLE
Error in drop_dir()

### ISSUE THREAD

**Issue by noamross** [karthik/rdrop2#3]
When I run drop_dir(), I get the following error:

```
Error: All select() inputs must resolve to integer column positions.
The following do not:
*  mime_type
```

This occurs in the last command, (`%>% dplyr::select(path, mime_type, root, bytes, modified)`.  When I run the command in debug mode, I find that `res$contents` does not have a `mime_type` column.

I also note that when I run with `verbose=TRUE`, I get this error:

```
Error in cat(list(...), file, sep, fill, labels, append) : 
  argument 3 (type 'list') cannot be handled by 'cat'
In addition: Warning message:
In if (value == "") next :
  the condition has length > 1 and only the first element will be used
```

This occurs in `pretty_lists()` when it attempts to print the `$content` element.

**Comment by karthik** [comment]
Thanks @noamross
Seems like `drop_dir()` listings are failing on empty folders since the length of `$contents` is `0`. Try installing from this new branch and see if the problem is fixed. Now, it returns a NULL if the a folder is empty.

```r
install_github("karthik/rdrop2@dir_fix")
```


```r
library(rdrop2)
drop_create("bar")
drop_dir("bar")
NULL
# remove folder
drop_delete("bar")
```

**Comment by karthik** [comment]
It would also help to know if you are running `drop_dir()` on your root (that contains some files), or is this on a sub-folder? `pretty_lists` should be able to handle any list (all it does it remove the extra white spaces and long lists are more compact on screen).

**Comment by noamross** [comment]
I was using drop_dir() on my root, which contains no files, only folders.  When I use it on a folder that contains files, I get no error.  (I note that the data frame in contents$res contains a `mime_type` column in the latter case.)

I get the same error on the `dir_fix` branch.  I think you have to check if the returned value includes all the expected columns, not just if `res$contents` is empty.

**Comment by karthik** [comment]
Ah, perfect. I'll add this in too.

**Comment by noamross** [comment]
`verbose = TRUE` still failing.  It appears that using `format()` on a data frame returns a data frame with all character columns of class `AsIs`, rather than a character vector, and `cat()` can't handle a data frame.
