### ISSUE TITLE
Error in credentials$access_token :    $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by moggces** [karthik/rdrop2#35]
Hi, 
I have tried both stable version and development version. 
I successfully completed the drop_auth(). 
However, when executing the other commands (e.g., drop_acc()), the same error was reported. 

Error in credentials$access_token :    $ operator is invalid for atomic vectors

Thanks!

My sessionInfo()
#######################

R version 3.1.1 (2014-07-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rdrop2_0.6.6.99

loaded via a namespace (and not attached):
[1] assertthat_0.1 digest_0.6.4   httr_0.4       magrittr_1.5   RCurl_1.95-4.3 stringr_0.6.2  tools_3.1.1

**Comment by karthik** [comment]
Hi @moggces 
If you download and install `stringr_0.6.1.tar.gz` from [here](http://cran.r-project.org/src/contrib/Archive/stringr/) and install locally (If you use RStudio you can choose that file from the menu)
Then restart R and run, does it solve the problem?

**Comment by karthik** [comment]
Alternate solution is to upgrade `httr` to dev version and `stringr` to `1.0.0`.

**Comment by moggces** [comment]
Thank you. 
After following this post " https://github.com/hadley/httr/issues/96", (basically I upgraded the httr package in another folder and copied & pasted to the system library folder).  I updated the "httr" package to 1.0 and now it works.
