### ISSUE TITLE
drop_dir cannot be fully silenced

### ISSUE THREAD

**Issue by oganm** [karthik/rdrop2#43]
https://github.com/karthik/rdrop2/blob/master/R/drop_dir.R#L48

Even when `n=0` a few lines leak due to tbl_df's print methods. It might be useful to make excecution of the print command depend on to value of `verbose` so it can be fully silenced when desired

**Comment by LiNk-NY** [comment]
@karthik I second this. Thanks!

**Comment by Fablepongiste** [comment]
@karthik any updates on this one ? 
I approve the issue raised  ! 
I actually think that if verbose = FALSE, nothing should be printed on thing at all, so n  = 0 should be default option.
