### ISSUE TITLE
two-factor auth

### ISSUE THREAD

**Issue by sckott** [karthik/rdrop2#5]
have you tested this on 2-factor auth?  i tried authing, and it didn't work, not sure if it's just me

**Comment by karthik** [comment]
Excellent question. It's not set up for 2FA. Even for GitHub I had to disable 2FA and just go with a strong password since it's really hard to do this for most CLI tools (defeats automation). I'll look into it but it will have to be in the second milestone.

**Comment by sckott** [comment]
ok

**Comment by karthik** [comment]
If you have examples of how this is done in CLI interfaces I'd love to see it.

**Comment by sckott** [comment]
nothing off the top
