### ISSUE TITLE
Request:  How easy would it be to make a function for file requests

### ISSUE THREAD

**Issue by hathawayj** [karthik/rdrop2#59]
Would be nice to create the request and tell it a folder where the request should go.

**Comment by ClaytonJY** [comment]
@hathawayj unfortunately this doesn't seem possible through the API: https://www.dropboxforum.com/t5/API-support/can-t-find-quot-File-Requests-API-quot/td-p/70629.

That post is over a year old, but I don't see anything about file requests in the v2 API docs either. Sorry!
