### ISSUE TITLE
transition to APIv2?

### ISSUE THREAD

**Issue by joelgombin** [karthik/rdrop2#60]
Dropxbox has announced [a while ago now](https://blogs.dropbox.com/developers/2016/06/api-v1-deprecated/) that it would be transitionning to a v2 of its API. Any plan to move `rdrop2` to the v2 too?

**Comment by karthik** [comment]
That is currently in the works. I hope to have something ready shortly.

**Comment by koendirckx** [comment]
Hi Karthik - any chance that this package will be updated in time for the v1 API deprecation? Thanks in advance!

**Comment by karthik** [comment]
@koendirckx Yes, it will be. Hoping to have this done this week.

**Comment by karthik** [comment]
In progress, due Sep 24th
