### ISSUE TITLE
how to read RData file ?

### ISSUE THREAD

**Issue by world9604** [karthik/rdrop2#66]
how to read RData file on shiny or local ???

**Comment by ClaytonJY** [comment]
For reading any kind of non-CSV from dropbox with this package, I always follow the pattern laid out by [`drop_read_csv`](https://github.com/karthik/rdrop2/blob/master/R/drop_read_csv.R), copied below

```r
drop_read_csv <- function(file, dest = tempdir(), dtoken = get_dropbox_token(), ...) {
    localfile = paste0(dest, "/", basename(file))
    drop_get(file, local_file = localfile, overwrite = TRUE, dtoken = dtoken)
    read.csv(localfile, ...)
}
```

The steps are
1. choose a filepath to save to (using `tempdir` is the right choice if you won't need the file again; let the OS worry about cleanup)
2. use `drop_get` to grab the target file and save it in the location from `1.`
3. read the newly-saved file from your local filesystem in whatever way you prefer

For your RDS use case, you might try writing something like this

```r
drop_read_rds <- function(file, dest = tempdir(), dtoken = get_dropbox_token(), ...) {
    localfile = paste0(dest, "/", basename(file))
    drop_get(file, local_file = localfile, overwrite = TRUE, dtoken = dtoken)
    readRDS(localfile, ...)
}
```

**Comment by ClaytonJY** [comment]
@world9604 did this work for you? If it did, you should close the issue.

**Comment by world9604** [comment]
I'm still using the below code but it's hasn't loaded yet

drop_load_RData <- function(file, dest = gsub('\\\\', '/', tempdir()), dtoken = get_dropbox_token(), ...) {
      localfile = paste0(dest, "/", basename(file))
      drop_get(file, local_file = localfile, overwrite = TRUE, dtoken = dtoken)
      print( localfile )
      load(localfile)
    }

**Comment by ClaytonJY** [comment]
That's my mistake; I read RData as RDS in your initial post.

When you call `load`,  it's loading all the objects into the environment as a side effect, and returns the names of those objects. When calling it in a function, that environment is the _function's_ environment, so you're loading all the variables, returning their names, and then throwing away the actual objects when the function completes.

Assuming you can't or don't want to change the RData file in Dropbox, I'd suggest adding a line to the very end of your function that returns the objects in the file as a list:

```r
drop_load_RData <- function(file, dest = gsub('\\', '/', tempdir()), dtoken = get_dropbox_token(), ...) {
  localfile = paste0(dest, "/", basename(file))
  drop_get(file, local_file = localfile, overwrite = TRUE, dtoken = dtoken)

  vars <- load(localfile)
  lapply(vars, get)   # return the objects in a list
}
```

If you only want one of the objects, you might do

```r
drop_load_RData_single <- function(file, name, dest = gsub('\\', '/', tempdir()), dtoken = get_dropbox_token(), ...) {
  localfile = paste0(dest, "/", basename(file))
  drop_get(file, local_file = localfile, overwrite = TRUE, dtoken = dtoken)

  load(localfile)
  get(name)  # return one object
```

In a longer-term view, I'd strongly suggest avoiding RData files in favor of RDS files; then it's only one object per file, the name doesn't come with it, and it doesn't require some of the oddness of the above functions.

Hope that helps!
