### ISSUE TITLE
Running tests deletes ALL folders in users account

### ISSUE THREAD

**Issue by ClaytonJY** [karthik/rdrop2#69]
Just realized this happened from when I was running tests late the other night...seems like undesirable behavior. Too busy restoring all my stuff to dig into they "why" right now; will do so later. Thank goodness Dropbox doesn't perma-delete right away!

**Comment by karthik** [comment]
yikes! That's why the tests are currently tied to an account that is not used. We do need to figure out a way to perhaps commit a httr token from a dummy account (and ensure that it doesn't read any other token). I'm very sorry you lost files while testing. :(

**Comment by ClaytonJY** [comment]
@karthik I didn't really lose anything, just had to hit "show deleted" and restore some stuff. Only a short panic!

I agree we need a more independent & safe way to test things; a dummy account might be the only way. I'll reach out to Dropbox next week to see if they can help us out. I suppose the quid-pro-quo would be aiming to be on this list: https://www.dropbox.com/developers/documentation/communitysdks. We aren't really an "app" so much as an SDK, I think? Bit of a grey line.

**Comment by ClaytonJY** [comment]
Fixed by @karthik in #99.
