### ISSUE TITLE
drop_upload should let us overwrite file

### ISSUE THREAD

**Issue by laresbernardo** [karthik/rdrop2#80]
Hello guys.
Love this library for scheduling reports and sharing with the team. The only problem I have is that I need to overwrite the files so everyone have the latest version. Hoy can I do this?
Thanks.

**Comment by karthik** [comment]
Thanks @laresbernardo 

Noted. We will keep this in mind for the upcoming update. #86 (closing since we already have an issue for this)

**Comment by karthik** [comment]
@laresbernardo This feature has been implemented and will appear on the next update.
