### ISSUE TITLE
drop_auth

### ISSUE THREAD

**Issue by karthik** [karthik/rdrop2#82]
Relevant URLs
```
/R/drop_auth.R: authorize = "https://www.dropbox.com/1/oauth2/authorize",
/R/drop_auth.R: access = "https://api.dropbox.com/1/oauth2/token"
```
Need to update auth to v2. 

Other notes:
- Perhaps print a message to the user that they add httr oauth files to their gitignore.

Notes from @scheidec

- Code: https://github.com/karthik/rdrop2/blob/master/R/drop_auth.R
- Change from v1: /1/oauth2/authorize to v2: /oath2/authorize
- V1 docs: https://www.dropbox.com/developers-v1/core/docs#oa2-authorize
- V2 docs: https://www.dropbox.com/developers/documentation/http/documentation#oauth2-authorize
- Only the path has changed, fixed in PR #75

access = "https://api.dropbox.com/1/oauth2/token"

- Code: https://github.com/karthik/rdrop2/blob/master/R/drop_auth.R
- Change from v1: /1/oauth2/token to v2: /oauth2/authorize
- V1 docs: https://www.dropbox.com/developers-v1/core/docs#oa2-token
- V2 docs: https://www.dropbox.com/developers/documentation/http/documentation#oauth2-token
- Only the path has changed, fixed in PR #75

**Comment by ClaytonJY** [comment]
Also need to update the docs apparently: https://travis-ci.org/karthik/rdrop2#L1946
