### ISSUE TITLE
drop_dir

### ISSUE THREAD

**Issue by karthik** [karthik/rdrop2#83]
Relevant URLs
```
metadata_url <- "https://api.dropbox.com/1/metadata/auto/"
```

Notes from @scheidec

- Code: https://github.com/karthik/rdrop2/blob/master/R/drop_dir.R
- Change from v1: /1/metadata to v2: /2/files/get_metadata
- Parameters, return values, and metadata have changed
- V1 docs: https://www.dropbox.com/developers-v1/core/docs#metadata
- V2 docs: https://www.dropbox.com/developers/documentation/http/documentation#files-get_metadata
- Metadata mapping: https://www.dropbox.com/developers/reference/migration-guide#metadata-mapping
- bytes -> size
- modified -> server_modified
- mime_type and root are no longer available in v2
- is_dir -> check if .tag=“folder”

**Comment by ClaytonJY** [comment]
Need to update docs as well https://travis-ci.org/karthik/rdrop2#L1955
