### ISSUE TITLE
drop_search

### ISSUE THREAD

**Issue by karthik** [karthik/rdrop2#84]
Relevant URLs

```
search_url <- "https://api.dropbox.com/1/search/auto/"
```

Notes from @scheidec

- Code: https://github.com/karthik/rdrop2/blob/master/R/drop_search.R
- Change from v1: /1/search to v2: /2/files/search
- Return values, metadata have changed
- V1 docs: https://www.dropbox.com/developers-v1/core/docs#search
- V2 docs: https://www.dropbox.com/developers/documentation/http/documentation#files-search
- Metadata mapping: https://www.dropbox.com/developers/reference/migration-guide#metadata-mapping
- modifier is now sharing_info/modified_by
- So maybe change to zz <- lapply(results, function(t) { t$sharing_info$modified_by = NULL; t })

**Comment by ClaytonJY** [comment]
also remove `data.table` dependency per #101
