### ISSUE TITLE
drop_delta

### ISSUE THREAD

**Issue by karthik** [karthik/rdrop2#85]
Relevant URLs

```
delta_url <- "https://api.dropbox.com/1/delta"
```

Notes from @scheidec

- Code: https://github.com/karthik/rdrop2/blob/master/R/drop_delta.R
- Change from v1: /1/delta to v2: /2/files/list_folder (with recursive=true)
- Parameters, return values, and metadata have changed
- V1 docs: https://www.dropbox.com/developers-v1/core/docs#delta
- V2 docs: https://www.dropbox.com/developers/documentation/http/documentation#files-list_folder
- path_prefix, locale, and cursor are no longer parameters in v2
- changes to cursor? Returned cursor makes calls to /2/files/list_folder/continue
- Metadata mapping: https://www.dropbox.com/developers/reference/migration-guide#metadata-mapping

**Comment by ClaytonJY** [comment]
also remove `data.table` dependency per #101

**Comment by ClaytonJY** [comment]
So, I actually added `drop_list_folder` and `drop_list_folder_continue` in #106 to power `drop_dir`. The docs for those do mention this delta-like usage pattern, but for that PR I just hid them underneath `drop_dir`. Need to think more about what needs to be done here.

**Comment by ClaytonJY** [comment]
At the very least, I should add `drop_list_folder_get_current_cursor` (or maybe a shorter name...) to wrap https://www.dropbox.com/developers/documentation/http/documentation#files-list_folder-get_latest_cursor. I think we can skip `long_poll`.

I could then export all these `drop_list_folder*` functions, but the output of `drop_list_folder` is a bit unwieldy compared to other things. I could add the cursor as an attribute to the output of `drop_dir`, and then have `drop_delta`/`drop_list_files_continue` take either a cursor or an object with a cursor attribute?

Just spitballing.
