### ISSUE TITLE
drop_upload

### ISSUE THREAD

**Issue by karthik** [karthik/rdrop2#86]
Relevant URLs

```
put_url <- "https://api-content.dropbox.com/1/files_put/auto/"
```

Notes from @scheidec

- Code: https://github.com/karthik/rdrop2/blob/master/R/drop_upload.R
- Change from v1: /1/files_put to v2: /2/files/upload
- Parameters, return values, metadata have changed
- V1 docs: https://www.dropbox.com/developers-v1/core/docs#files_put
- V2 docs: https://www.dropbox.com/developers/documentation/http/documentation#files-upload
- ‘Overwrite’ is now part of the v2 ‘mode’ parameter, which lets you specify “overwrite”, “add”, or - “update” for file conflicts
- Metadata mapping: https://www.dropbox.com/developers/reference/migration-guide#metadata-mapping

**Comment by ClaytonJY** [comment]
Closed in #102
