### ISSUE TITLE
drop_history

### ISSUE THREAD

**Issue by karthik** [karthik/rdrop2#89]
Relevant URLs

```
rev_url <- "https://api.dropbox.com/1/revisions/auto/"
```

Notes from @scheidec

- https://github.com/karthik/rdrop2/blob/master/R/drop_history.R
- Change from v1: /1/revisions to v2: /2/files/list_revisions
- Return values and metadata have changed
- V1 docs: https://www.dropbox.com/developers-v1/core/docs#revisions
- V2 docs: https://www.dropbox.com/developers/documentation/http/documentation#files-list_revisions
- No reference of any return values in script as is

**Comment by ClaytonJY** [comment]
also remove `data.table` dependency per #101
