### ISSUE TITLE
drop_acc

### ISSUE THREAD

**Issue by karthik** [karthik/rdrop2#90]
Relevant URLs

```
url <- "https://api.dropbox.com/1/account/info"
```

Notes from @scheidec

- Code: https://github.com/karthik/rdrop2/blob/master/R/drop_acc.R
- Change from v1: /1/account/info to v2: /2/users/get_current_account
- Parameters and return values have changed
- V1 docs: https://www.dropbox.com/developers-v1/core/docs#account-info
- V2 docs: https://www.dropbox.com/developers/documentation/http/documentation#users-get_current_account
- No reference to any parameters or return values in script as is
- HTTP request method changed from GET in v1 to POST in v2

**Comment by ClaytonJY** [comment]
@karthik we can't avoid breaking changes, which makes me wonder if we should even bother with half-backwards-compatibility.

I started writing code to coerce the new response for `drop_acc` to be like the old, but it's not quite possible. `uid` has been replaced with `account_id`, getting quota information requires a separate call with returns only 2 of the 4 old fields.

drop_acc is especially odd; custom formatting is with special internal functions, coercing a non-tabular dataset to a data.frame, verbose fundamentally changing the output object, etc.

I'd much rather simply return the nested list we get back automatically. This will break anything that might rely on it; more effort could be made to break less stuff, I suppose?

What's the right thing to do here?

**Comment by karthik** [comment]
I think it seems ok to break drop_acc. Much of the old format is quite dated and it's easier to work with a list. We could write another function to retrieve quota information, and if necessary, a very thin helper function to return a nice tibble from drop_acc + drop_acc_quota without any special internal functions.

**Comment by karthik** [comment]
I strongly doubt that it will break anything critical and we can include some notes for migration that documents this change. Perhaps a special section in the README that documents breaking changes clearly.
