### ISSUE TITLE
drop_media

### ISSUE THREAD

**Issue by karthik** [karthik/rdrop2#92]
Relevant URLs

```
media_url <- "https://api.dropbox.com/1/media/auto/"
```

Notes from @scheidec

- Code: https://github.com/karthik/rdrop2/blob/master/R/drop_media.R
- Change from v1: /1/media to v2: /2/files/get_temporary_link
- Parameters, return values, metadata have changed
* V1 docs: https://www.dropbox.com/developers-v1/core/docs#media
* v2 docs: https://www.dropbox.com/developers/documentation/http/documentation#files-get_temporary_link
* ‘locale’ no longer a parameter

**Comment by karthik** [comment]
@scheidec Would you be interested in taking this on? No worries if you’re busy. 
cc @ClaytonJY

**Comment by scheidec** [comment]
@karthik Yes, I can work on this one

**Comment by ClaytonJY** [comment]
Closed in #102
