### ISSUE TITLE
R CMD check failing due to improper auth flow

### ISSUE THREAD

**Issue by ClaytonJY** [karthik/rdrop2#94]
https://travis-ci.org/karthik/rdrop2#L2029

I'm experimenting with what's going on here. Updated all packages to try and match environment; can run tests which properly grab `.httr-oauth`, but R CMD Check locally hangs on the tests due to not being able to auth. Don't get quite the same errors travis does.

cc @karthik

**Comment by ClaytonJY** [comment]
I don't know why, but the test code doesn't seem to be finding the `.httr-oauth` file. Seems this has changed, possible due to updates in `httr` or `testthat`.

Jenny Bryan has been using an RDS token for testing `googlesheets`: https://github.com/jennybc/googlesheets/blob/master/tests/testthat/googlesheets_token.rds.enc, maybe we should too? Would be as easy as changing the test I just wrote for `drop_auth` (#95) to pull read the RDS token, and then replacing `.httr-oauth.enc` with `dropbox_token.rds.enc`, and updating the travis file to match.

**Comment by karthik** [comment]
Currently investigating this. It's happening for me as well.

**Comment by karthik** [comment]
> Would be as easy as changing the test I just wrote for drop_auth (#95) to pull read the RDS token, and then replacing .httr-oauth.enc with dropbox_token.rds.enc, and updating the travis file to match.

That's the workflow I updated right before I left. I just noticed that I forgot to push my changes, but I'm debugging this now. Stay tuned.
